apiVersion: v1
kind: Endpoints
metadata:
  name: k8s-http-api 
  namespace: kube-system
subsets:
  - addresses:
      - ip: 172.31.78.215
      - ip: 172.31.78.216
      - ip: 172.31.78.217
    ports:
      - port: 8080
        protocol: TCP
        name: http
