kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: file-server-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: file-server
    spec:
      containers:
        - name: file-server
          image: file-server
          imagePullPolicy: IfNotPresent
          command:
            - /file-server
          args:
            - -p
            - "80"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - name: files
              mountPath: /mnt
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
      nodeSelector:
        fileserver: "true"
      volumes:
        - name: files
          hostPath:
            path: /opt/app
        - name: host-time
          hostPath:
            path: /etc/localtime
