kind: Service
apiVersion: v1
metadata:
  name: file-server
spec:
  type: ClusterIP
  clusterIP: 10.254.0.21
  ports:
    - port: 80
      targetPort: 80
      name: httpk
  selector:
    component: file-server
