apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: datacentre
  name: cassandra
spec:
  serviceName: "cassandra"
  podManagementPolicy: Parallel
  replicas: 3
  template:
    metadata:
      labels:
        component: cassandra
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: chk-svc
          image: alpine:latest 
          command:
            - /bin/sh
            - -c
            - "for i in $(seq -s ' ' 1 60); do sleep 1; if getent hosts cassandra-seed.datacentre; then exit 0; fi; done; exit 1"
      containers:
        - name: cassandra
          image: 172.31.78.217:5000/cassandra:v3
          command: ["/entrypoint.sh"]
          env:
            - name: DSCV
              value: "cassandra-seed"
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: dc-config
                  key: cassandra.cluster-name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TRIES
              valueFrom:
                configMapKeyRef:
                  name: dc-config
                  key: tries
          ports:
            - containerPort: 7000 
            - containerPort: 7199 
            - containerPort: 9042 
            - containerPort: 9160 
          volumeMounts:
            - name: gluster-volume
              mountPath: "/mnt"
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: gluster-volume
          persistentVolumeClaim:
            claimName: glusterfs-pvc
        - name: host-time
          hostPath:
            path: /etc/localtime
