apiVersion: v1
kind: Service
metadata:
  namespace: datacentre
  labels:
    component: cassandra-seed
  name: cassandra-seed
spec:
  clusterIP: None
  selector:
    component: cassandra-seed
  ports:
    - name: peer
      port: 7000
      targetPort: 7000
    - name: rpc
      port: 9160 
      targetPort: 9160
    - name: jmx
      port: 7199 
      targetPort: 7199
    - name: cql
      port: 9042 
      targetPort: 9042
