apiVersion: v1
kind: Endpoints
metadata:
  name: harbor 
subsets:
- addresses:
  - ip: 172.31.78.216
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443 
    protocol: TCP
    name: https
  - port: 4443 
    protocol: TCP
    name: msn
