apiVersion: v1
kind: Service
metadata:
  name: harbor 
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443 
    protocol: TCP
    targetPort: 443
    name: https
  - port: 4443 
    protocol: TCP
    targetPort: 4443
    name: msn
