apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: gitlab
  name: gitlab-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "k8s-volume"
    readOnly: false

